[package]
name = "Timer"
version = "0.1.0"
edition = "2024"

[lib]
name = "timer"

[dependencies]
iced = { version ="0.14", features = ["tokio"] }
toml = "0.9.8"
serde = {version = "1.0.228", features = ["derive"]}
reqwest = "0.12.24"
anyhow = "1.0.100"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", default-features = false, features = ["std", "fmt", "json", "time", "local-time"] }
